#!/bin/bash

# Number of pages to check in PDF
PAGECOUNT=1
# File path
filepath="$1"

echo "Start extracting ISBN from barcode."
echo "Extract from $(basename "$filepath")"

# If the file extension is not pdf
shopt -s nocasematch
if [[ ! $1 =~ .+(\.pdf)$ ]]; then
  echo "[ERROR] This file is not PDF."
  exit 1
fi
shopt -u nocasematch

# Delete all .image* generated by pdfimages
rm -f .image*

# Get total count of PDF pages
pages=$(pdfinfo "$filepath" | grep -E "^Pages" | sed -E "s/^Pages: +//") &&
# Generate JPEG from PDF
pdfimages -j -l "$PAGECOUNT" "$filepath" .image_h &&
pdfimages -j -f $((pages - PAGECOUNT)) "$filepath" .image_t &&
# Grep ISBN
isbnTitle="$(zbarimg -q .image* | sort | uniq | grep -E '^EAN-13:978' | sed -E 's/^EAN-13://').pdf" &&
# If the ISBN was found, rename PDF file to "ISBN.pdf"
[ "$isbnTitle" != ".pdf" ] &&
mv "$filepath" "$(dirname "$filepath")/$isbnTitle" && rm -f .image* && exit 0 ||
# Else, exit with error code
rm -f .image* && exit 1
